---
language: objective-c
osx_image: xcode7

before_install:
  - curl -sL https://gist.github.com/henrikhodne/7ac6d02ff9a24a94720c/raw/install_appledoc.sh | sh

install: 
 - sudo easy_install cpp-coveralls

script: 
 - xctool -project DTFoundation.xcodeproj -scheme "DTSidePanels Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTFoundation.xcodeproj -scheme "DTReachability Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTFoundation.xcodeproj -scheme "DTZipArchive Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTFoundation.xcodeproj -scheme "DTProgressHUD Demo" build -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO
 - xctool -project DTFoundation.xcodeproj -scheme "Static Library" build test -sdk iphonesimulator -arch i386 ONLY_ACTIVE_ARCH=NO -configuration Coverage
 - xctool -project DTFoundation.xcodeproj -scheme "DTFoundation (iOS)" test -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6 Plus'
 - xctool -project DTFoundation.xcodeproj -scheme "DTFoundation (OSX)" clean build
 - appledoc -o /tmp .

after_success:
  - ./coveralls.rb --extension m --exclude-folder Demo --exclude-folder Test --exclude-folder Externals
